### ISSUE TITLE
Basic-table: Revert back noRowsOverlayComponentParams prop

### ISSUE THREAD

**Issue by antonantonovich** [Infineon/infineon-design-system-stencil#1623]
### Detailed description of how to reproduce the problem

Table not rendered and Exception logged:
index.js:52  TypeError: params.noRowsMessageFunc is not a function
    at CustomNoRowsOverlay.init (customNoRowsOverlay.ts:10:1)

That was broken after commit https://github.com/Infineon/infineon-design-system-stencil/commit/c35ce5e1ec6da900cf6931b33302a28fdfe8ae31 where params were deleted

```
-     noRowsOverlayComponentParams: {
-        noRowsMessageFunc: () =>
-          'No rows found at: ' + new Date().toLocaleTimeString(),
-      },
```

### Upload a screenshot

![image](https://github.com/user-attachments/assets/ace08562-7f3f-40e4-9faa-7379d0e9730b)
![image](https://github.com/user-attachments/assets/d3775c5c-f7bd-4659-8b9a-a9d5b9bd4c34)

### Expected behavior

Table should render

**Comment by tishoyanchev** [comment]
@antonantonovich 
Hi, thank you for your submission. 
Can you please provide more details about this issue? 
Which table, basic or advanced, and what is your environment? How are you trying to render the table? 
For me both tables render without any issues.

**Comment by antonantonovich** [comment]
Basic table. I use react wrapper like that.
```
 <IfxBasicTable
                  cols='[{"headerName":"Make","field":"make","sortable":true,"sort":"desc","unSortIcon":true},{"headerName":"Model","field":"model","sortable":true,"unSortIcon":true}]'
                  rows='[{"make":"Toyota","model":"Celica","price":35000,"age":10},{"make":"Ford","model":"Mondeo","price":32000,"age":12},{"make":"Porsche","model":"Boxster","price":72000}]'
                  table-height='auto'>
                </IfxBasicTable>
```

**Comment by tishoyanchev** [comment]
@antonantonovich 
I can't reproduce the issue. 
Maybe try cleaning the cache and pull again the latest version if you haven't already? 
There were some major releases recently, make sure your version is up to date, clean the cache, and try again. 
Try isolating the table from the rest of your code to test if the code isn't affecting the table somehow. 
In this commit https://github.com/Infineon/infineon-design-system-stencil/commit/c35ce5e1ec6da900cf6931b33302a28fdfe8ae31 I simply re-introduced the dynamic update of cols and rows + streamlined some of the code. There is nothing essentially "new".

**Comment by antonantonovich** [comment]
you removed the property noRowsMessageFunc in that commit that was introduced 10 month ago.
that property used in CustomNoRowsOverlay component
That component inited createGrid(this.container, this.gridOptions); line

I don't know how it works for you and how it supposed to work. 

![image](https://github.com/user-attachments/assets/aac12bbb-1074-4222-9e0f-96ac9e3d14a9)

**Comment by antonantonovich** [comment]
That's not "new", that's a regression. noRowsOverlayComponent was introduced long ago and now it broken

**Comment by tishoyanchev** [comment]
Your [issue](https://github.com/orgs/Infineon/projects/4?pane=issue&itemId=89490963&issue=Infineon%7Cinfineon-design-system-stencil%7C1623) has been approved! You can follow the latest status on our [public backlog board](https://github.com/orgs/Infineon/projects/4/views/1?pane=info). Thank you for your contribution!

**Comment by tishoyanchev** [comment]
@antonantonovich 
`noRowsOverlayComponent` property is not removed. Only the `noRowsOverlayComponentParams` was removed, which sets the `noRowsMessageFunc`, which adds a message when cells are empty. This property is not responsible for the initiation of the table, and the issue you are facing. 
As I am not able to reproduce this issue, I have to once again ask you to please look into your code to make sure you are using the latest version of our package, clean the cache, and if the issue is still occurring, then please provide more context about how you are using the table.

**Comment by antonantonovich** [comment]
Yes, noRowsOverlayComponentParams removed as I showed on screenshot. But that property provided noRowsMessageFunc which is required by the component CustomNoRowsOverlay. That overlay displayed when table initially has no data and that causes aggrid failure.

As we using react wrapper -- all properties updated dynamically. When we initially render the table -- we have no rows. And then when rows comes, we expect from table to be updated. 
And the problem is that when table was rendered initially with empty rows -- it failed to construct aggrid due to CustomNoRowsOverlay fail. When we pass rows after it -- nothing happened because aggrid not built.
